[tool.poetry]
name = "traffic-light-project"
version = "0.1.0"
description = ""
authors = ["Timothy Regan <tregan@pillartechnology.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.0"
jupyter = "^1.0.0"
ipykernel = "^5.4.2"
presto-python-client = "^0.7.0"
plotly = "^4.14.1"
matplotlib = "^3.3.3"
shapely = "^1.7.1"
geopandas = "^0.8.1"
geojson = "^2.5.0"
h3 = "^3.7.2"
charset_normalizer = "^1.3.6"
retry = "^0.9.2"
descartes = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
